name: Deploy

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Production Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for production
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      - name: Upload production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-release
          path: dist/
          retention-days: 30

      - name: Deployment summary
        run: |
          echo "✅ Production build completed successfully!"
          echo "📦 Build size: $(du -sh dist/ | cut -f1)"
          echo "🚀 Ready for deployment"
          echo ""
          echo "Next steps:"
          echo "- Download artifacts from this workflow"
          echo "- Deploy to your hosting provider (Vercel, Netlify, etc.)"
          echo "- Or use automatic deployment (configure secrets for your platform)"
